
--BOLETOS RECEBIDOS QUE JÁ FORAM PAGOS
SELECT BLT.*, CLI.DHINTEGRACAO
FROM BOLETO BLT
JOIN CLIENTE CLI ON (CLI.TPCLIENTE = BLT.TPCLIENTE AND
                     CLI.CPFCNPJ   = BLT.CPFCNPJ)
WHERE ((ISNULL(BLT.IDMENSAGEMREC, 0) > 0) OR
       ((ISNULL(BLT.IDARQUIVOREC, 0) > 0)))
  AND ISNULL(BLT.VALORPAGO, -1) > -1

--BOLETOS RECEBIDOS QUE AINDA NÃO FORAM PAGOS
SELECT BLT.*, CLI.DHINTEGRACAO
FROM BOLETO BLT
JOIN CLIENTE CLI ON (CLI.TPCLIENTE = BLT.TPCLIENTE AND
                     CLI.CPFCNPJ   = BLT.CPFCNPJ)
WHERE ((ISNULL(BLT.IDMENSAGEMREC, 0) > 0) OR
       ((ISNULL(BLT.IDARQUIVOREC, 0) > 0)))
  AND ISNULL(BLT.VALORPAGO, -1) = -1

